spring:
  datasource:
    url: jdbc:h2:C:/study/spring_boot/MyApplicationH2/students
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
server:
  port: 8082